ministryofjustice/hmpps-resettlement-passport-api

helm_deploy/hmpps-resettlement-passport-api/files/stubs/interventions-service-api/__files/getPrisonerReferrals-G4161UF-200-response.json, helm_deploy/hmpps-resettlement-passport-api/files/stubs/interventions-service-api/__files/getPrisonerReferrals-G4274GN-200-response.json
=> Changes to attitudes-thinking-behaviour test stubs

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/AttitudesThinkingAndBehaviourResettlementAssessmentStrategy.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/AccommodationResettlementAssessmentStrategyTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/AttitudesThinkingAndBehaviourResettlementAssessmentStrategyTest.kt
**Changes made**
- Add questions to attitudes, thinking & behaviour assessment pathway
- Unit tests for attitudes, thinking & behaviour
- Small fix for Accommodation unit test
=> PSFR-1065/attitudes-behaviour-question-pages

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/DrugsAndAlcoholResettlementAssessmentStrategy.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/DrugsAndAlcoholResettlementAssessmentStrategyTest.kt
- Drugs and alcohol assessment
- Unit tests
=> PSFR-1067: add drugs and alcohol assessment

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/FinanceAndIdResettlementAssessmentStrategy.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/FinanceAndIdResettlementAssessmentStrategyTest.kt
- Add Finance and ID assessment
- Unit tests
=> PSFR-1069/finance-and-id

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/data/LicenceConditions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/external/CvlApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/external/CvlApiServiceTest.kt
- add licence start date
- add licence end date
- add sequence of licence conditions
=> PLT-57 add missing licence condition mapping

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/AttitudesThinkingAndBehaviourResettlementAssessmentStrategy.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/AttitudesThinkingAndBehaviourResettlementAssessmentStrategyTest.kt
Reduced number of questions and adjusted wording
=> PSFR-933 Adjust attitudes thinking and behaviour assessment

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/data/Prisoners.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/external/PrisonerSearchApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/PrisonersDetailsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/PoPUserOTPServiceTest.kt, src/test/resources/testdata/expectation/prisoner-details-1.json, src/test/resources/testdata/expectation/prisoner-details-3.json, src/test/resources/testdata/expectation/prisoner-details-4.json, src/test/resources/testdata/sql/seed-pathway-statuses-10.sql
New bool should only be true if the BSCT2 has been completed and the resettlement review hasn't been
=> PSFR-1121: added resettlementReviewAvailable boolean 

.circleci/config.yml, Dockerfile, build.gradle.kts, docker-compose.yml, gradle/wrapper/gradle-wrapper.properties, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/config/ResourceServerConfiguration.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/SecurityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/resource/EndpointSecurityCheck.kt
* Java 19 -> 21 - his enables upgrade to hmpps-sqs-spring-boot-starter and the older version that supported java 19 came with security issues.
* Upgrade dependencies
=> PSFR-855 Update dependencies and image

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/AbstractResettlementAssessmentStrategy.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/AccommodationResettlementAssessmentStrategyTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/AttitudesThinkingAndBehaviourResettlementAssessmentStrategyTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/ChildrenFamiliesAndCommunitiesStrategyTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/DrugsAndAlcoholResettlementAssessmentStrategyTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/EducationSkillsAndWorkResettlementStrategyTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/FinanceAndIdResettlementAssessmentStrategyTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/HealthResettlementAssessmentStrategyTest.kt
Change hardcoded titles to be dynamic on FE
=> PSFR-1150: remove report summary title

helm_deploy/hmpps-resettlement-passport-api/files/stubs/resettlement-passport-and-delius-api/mappings/postPrisonerAppointments-200.json, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/data/deliusapi/AppointmentsDTO.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/resource/AppointmentsResourceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/AppointmentsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/DeliusContactService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/external/ResettlementPassportDeliusApiService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/config/PostgresContainer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/AppointmentsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/ResettlementPassportDeliusApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/AppointmentsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/api/ResettlementPassportDeliusApiServiceTest.kt, src/test/resources/testdata/expectation/appointments-2.json, src/test/resources/testdata/sql/seed-pathway-statuses-6.sql
* Post create appointment calls to delius API
* Remove code that reads appointments from DB
=> PSFR-1128 appointments

build.gradle.kts
In addition update some test dependencies
=> Update to dps gradle-spring-boot 5.15.6

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/data/PoPUserResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/resource/PopUserOTPResourceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/PoPUserOTPService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/PoPUserOTPServiceTest.kt, src/test/resources/testdata/expectation/pop-user-otp-post-result-2.json, src/test/resources/testdata/expectation/pop-user-otp-post-result.json, src/test/resources/testdata/expectation/pop-user-otp.json
=> PLT-268 Pentest fix - remove prisoner and dob in the GET & POST  response

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/data/Watchlist.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/jpa/entity/WatchlistEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/jpa/repository/WatchlistRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/resource/WatchlistResourceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/WatchlistService.kt, src/main/resources/db/migration/V1_42_add_new_watchlist_table_to_database.sql
Created files:
**PSFR - 1303** - V1_42_add_new_watchlist_table_to_database.sql: Added SQL migration script to create a new watchlist table in the database.
**PSFR - 1304** - WatchlistResourceController.kt: Added WatchlistResourceController to handle POST request.
**WatchlistEntity.kt:** Created WatchlistEntity to connect watchlist data between the database and the app.
**WatchlistRepository.kt:** Created WatchlistRepository to manage watchlist data in the database.
**WatchlistService.kt:** Created WatchlistService to handle watchlist functionality in app.
=> PSFR-1303/1304: created watchlist database table and POST endpoint

helm_deploy/hmpps-resettlement-passport-api/files/stubs/__files/resettlement-passport-and-delius-api-getAppointments-A8731DY-200-response.json
for PLT-281 we require a next working day appointment
=> update for appointment to be next working day

README.md, helm_deploy/hmpps-resettlement-passport-api/files/stubs/__files/resettlement-passport-and-delius-api-getAppointments-A8731DY-200-response.json, stubs.Dockerfile
https://wiremock.org/docs/response-templating/
=> PLT-227: Change appointment stub data to be dynamic

README.md, helm_deploy/hmpps-resettlement-passport-api/files/stubs/__files/resettlement-passport-and-delius-api-getAppointments-A8731DY-200-response.json, stubs.Dockerfile
Reverts ministryofjustice/hmpps-resettlement-passport-api#353
=> Revert "PLT-227: Change appointment stub data to be dynamic"

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/jpa/repository/WatchlistRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/WatchlistService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/external/PrisonerSearchApiService.kt
object mapper speed increased from 2s to 185ms
=> PSFR-1369 - remove n+1 watchlist query

helm_deploy/hmpps-resettlement-passport-api/files/stubs/__files/cvl-api-getLicenceById-G4161UF-200-response.json
Updated LC for G416UF so that we can test  ],
"changeStatus": false
} flag now set in API
=> PLT-291-Update cvl-api-getLicenceById-G4161UF-200-response.json

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/resource/LicenceConditionResourceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/LicenceConditionService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/PoPUserMetricsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/LicenceConditionIntegrationTest.kt, src/test/resources/testdata/expectation/licence-condition-1.json
=> PLT-259 Including parameter for changesStatus flag to get updated only for PLT calls

.trivyignore, build.gradle.kts, docker-compose-local.yml, helm_deploy/hmpps-resettlement-passport-api/values.yaml, helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/config/ResourceServerConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/events/OffenderEventEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/events/OffenderEventRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/events/OffenderEventsListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/events/OffenderEventsService.kt, src/main/resources/application-dev.yml, src/main/resources/application-offender-events.yml, src/main/resources/db/migration/V1_48__offender-events.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/config/LocalStackContainer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/events/OffenderEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/helpers/TestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/PathwayIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/resource/EndpointSecurityCheck.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/RetryConfigTest.kt, src/test/resources/application-test.yml, src/test/resources/testdata/events/intake-event.json, src/test/resources/testdata/events/recall-event.json, src/test/resources/testdata/sql/clear-all-data.sql, src/test/resources/testdata/sql/seed-prisoners-for-events.sql
* Process prison receive and release events and store in new events table
* Try to determine when event is a recall
* Upgrade spring-boot to be compatible with the latest `hmpps-sqs-spring-boot-starter` 
Note this only runs in dev at the moment, not preprod or prod
=> PLT-373 Process offender events

helm_deploy/values-preprod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/events/OffenderEventEntity.kt, src/main/resources/db/migration/V1_49_offender_events_enums.sql
* Enable events on preprod
* Fix enums persisting as ordinal instead of name
=> PLT-373 enable events on preprod

helm_deploy/hmpps-resettlement-passport-api/files/stubs/__files/cvl-api-getLicenceById-B1234ZX-200-response.json
Make licence conditions date change only daily otherwise every call will assume the licence conditions have changed minute by minute
=> PLT-403: amend stub for licence conditions

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/data/LicenceConditions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/LicenceConditionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/LicenceConditionIntegrationTest.kt
Reverts ministryofjustice/hmpps-resettlement-passport-api#419
=> Revert "PLT-403 amend seen licence updates"

helm_deploy/hmpps-resettlement-passport-api/files/stubs/__files/prisoner-search-api-getPrisonerDetails-B1234ZX-200-response.json
Reverts ministryofjustice/hmpps-resettlement-passport-api#434
=> Revert "Update prisoner-search-api-getPrisonerDetails-B1234ZX-200-response.json"

helm_deploy/hmpps-resettlement-passport-api/Chart.yaml, helm_deploy/hmpps-resettlement-passport-api/values.yaml
So that volume properties are included in the result
=> PLT-404 Update generic-service helm template

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/PathwayAndStatusService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/PathwayAndStatusServiceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/PathwayAndStatusServiceTest.kt
=> PLT-426 Handle unique constraint violation

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/ResettlementAssessmentIntegrationTest.kt
Run cleanup before rather than after, for comfyness.
=> Order some data before asserts for test stability

helm_deploy/hmpps-resettlement-passport-api/values.yaml
=> PLT-435 Gotenberg Integration for the PDF Conversion - gotenberg deployment fix

applicationinsights.json, build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/resource/PrisonerResourceController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/LicenceConditionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/RisksIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/AllocationManagerApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/ArnApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/CaseNotesApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/CvlApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/EducationEmploymentApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/HmppsAuthMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/InterventionsServiceApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/KeyWorkerApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/PoPUserApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/PrisonRegisterApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/PrisonerSearchApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/ResettlementPassportDeliusApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/wiremock/WireMockServerBase.kt
Reduce applicationinsights logging
Use random available port for wiremocks
=> PSFR-1514 Try adding trace annotation

src/main/resources/assessment-config/education-skills-and-work/education-skills-and-work-v1.yml, src/main/resources/assessment-config/finance-and-id/finance-and-id-assessment-v1.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/EducationSkillsAndWorkResettlementAssessmentAssessmentStrategyTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/FinanceAndIdV1ResettlementAssessmentAssessmentStrategyTest.kt
Added the "Select all that apply." text to all checkbox questions which didn't have a subTitle
=> PSFR-1599 - Add in subTitle to all checkbox questions

src/main/resources/assessment-config/education-skills-and-work/education-skills-and-work-v2.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/EducationSkillsAndWorkV2ResettlementAssessmentStrategyTest.kt
=> PSFR-1588-FIX

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/ResettlementAssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/AssessmentUtils.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/ResettlementAssessmentStrategy.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/ResettlementAssessmentServiceTest.kt
…Fix for multiple Answer in Submit
=> PLT-477 Profile tags for Personalised Content - Code reusability and Fix for Multiple Answers in Submit

Dockerfile, docker-compose.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/config/CachingConfiguration.kt
In addition:
* Improve docker image cachability (version being at the top invalidated loads of stuff)
* Fix redis config in docker-compose.yml
=> PSFR-1384 Add app version to cache config

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/jpa/entity/TodoEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/jpa/repository/PrisonerRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/jpa/repository/TodoRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/resource/TodoResourceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/TodoService.kt, src/main/resources/db/migration/V1_61__todo.sql, src/main/resources/db/migration/V1_62__todo.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/TodoIntegrationTest.kt, src/test/resources/testdata/expectation/todo-get-response.json, src/test/resources/testdata/expectation/todo-patch-response.json, src/test/resources/testdata/expectation/todo-update-response.json, src/test/resources/testdata/expectation/todo-with-2-items.json, src/test/resources/testdata/sql/clear-all-data.sql, src/test/resources/testdata/sql/seed-1-prisoner.sql
Endpoints to support created todo lists for people on probation
=> PLT-528 Todo list endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/ResettlementAssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/resettlementassessmentstrategies/ResettlementAssessmentStrategy.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/service/ResettlementAssessmentServiceTest.kt
Keep the questions in order of the YAML file
=> PSFR-1787 - Ordering of Report Information Nested questions

src/main/resources/db/migration/V1_66__remove_crn_prisoner.sql
Don't merge this till after the previous code is release to prod
=> PSFR-1967 - Added back in 'Remove CRN' DB script

helm_deploy/values-prod.yaml
The helm chart fails to generate without this
=> RSP-1841: Set business hours to false for production DB connection alert

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/resource/CaseAllocationResourceController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/CaseAllocationIntegrationReadOnlyModeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsresettlementpassportapi/integration/ResettlementAssessmentIntegrationReadOnlyModeTest.kt, src/test/resources/testdata/sql/seed-1-prisoner-case-allocation.sql
- Controlled via read only mode feature flag.
=> [RSP-2077] Controlled access to case allocation POST,PATCH endpoints

helm_deploy/values-dev.yaml
Reverts ministryofjustice/hmpps-resettlement-passport-api#682
=> [RSP-0000] Switch on read only mode on dev.

helm_deploy/values-dev.yaml
Reverts ministryofjustice/hmpps-resettlement-passport-api#683
=> [RSP-0000] Switch off read only mode on dev.
